// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

const TableNameCliServerInfo = "cli_server_info"

// CliServerInfo mapped from table <cli_server_info>
type CliServerInfo struct {
	IPSSH      string `gorm:"column:ip_ssh;primaryKey" json:"ip_ssh"`
	IPInternal string `gorm:"column:ip_internal" json:"ip_internal"`
	Name       string `gorm:"column:name" json:"name"`
	Pass       string `gorm:"column:pass" json:"pass"`
	Role       string `gorm:"column:role" json:"role"`
	Type       string `gorm:"column:type" json:"type"`
	User       string `gorm:"column:user" json:"user"`
}

// TableName CliServerInfo's table name
func (*CliServerInfo) TableName() string {
	return TableNameCliServerInfo
}
