// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

const TableNameCliUserNeMapping = "cli_user_ne_mapping"

// CliUserNeMapping mapped from table <cli_user_ne_mapping>
type CliUserNeMapping struct {
	UserID  int64 `gorm:"column:user_id;primaryKey" json:"user_id"`
	TblNeID int64 `gorm:"column:tbl_ne_id;primaryKey" json:"tbl_ne_id"`
}

// TableName CliUserNeMapping's table name
func (*CliUserNeMapping) TableName() string {
	return TableNameCliUserNeMapping
}
