// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

import (
	"time"
)

const TableNameCliOperationHistory = "cli_operation_history"

// CliOperationHistory mapped from table <cli_operation_history>
type CliOperationHistory struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IsOssType      int32     `gorm:"column:is_oss_type" json:"is_oss_type"`
	CmdName        string    `gorm:"column:cmd_name;not null" json:"cmd_name"`
	FunctionName   string    `gorm:"column:function_name;default:Configuration Management" json:"function_name"`
	CreatedDate    time.Time `gorm:"column:created_date;not null" json:"created_date"`
	ExecutedTime   time.Time `gorm:"column:executed_time" json:"executed_time"`
	NeIP           string    `gorm:"column:ne_ip" json:"ne_ip"`
	NeName         string    `gorm:"column:ne_name" json:"ne_name"`
	Scope          string    `gorm:"column:scope" json:"scope"`
	Result         string    `gorm:"column:result" json:"result"`
	Account        string    `gorm:"column:account;not null" json:"account"`
	IPAddress      string    `gorm:"column:ip_address" json:"ip_address"`
	InputType      string    `gorm:"column:input_type" json:"input_type"`
	TimeToComplete int64     `gorm:"column:time_to_complete" json:"time_to_complete"`
	NeID           int32     `gorm:"column:ne_id" json:"ne_id"`
	Session        string    `gorm:"column:session" json:"session"`
	BatchID        string    `gorm:"column:batch_id" json:"batch_id"`
}

// TableName CliOperationHistory's table name
func (*CliOperationHistory) TableName() string {
	return TableNameCliOperationHistory
}
