// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

const TableNameCliNeSlave = "cli_ne_slave"

// CliNeSlave mapped from table <cli_ne_slave>
type CliNeSlave struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NeID      int64  `gorm:"column:ne_id;not null" json:"ne_id"`
	IPAddress string `gorm:"column:ip_address" json:"ip_address"`
	Port      int32  `gorm:"column:port" json:"port"`
}

// TableName CliNeSlave's table name
func (*CliNeSlave) TableName() string {
	return TableNameCliNeSlave
}
