// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

import (
	"time"
)

const TableNameCliLoginHistory = "cli_login_history"

// CliLoginHistory mapped from table <cli_login_history>
type CliLoginHistory struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserName  string    `gorm:"column:user_name;not null" json:"user_name"`
	IPAddress string    `gorm:"column:ip_address" json:"ip_address"`
	TimeLogin time.Time `gorm:"column:time_login" json:"time_login"`
}

// TableName CliLoginHistory's table name
func (*CliLoginHistory) TableName() string {
	return TableNameCliLoginHistory
}
