// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

const TableNameCliNe = "cli_ne"

// CliNe mapped from table <cli_ne>
type CliNe struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Description string `gorm:"column:description" json:"description"`
	IPAddress   string `gorm:"column:ip_address" json:"ip_address"`
	Name        string `gorm:"column:name" json:"name"`
	Namespace   string `gorm:"column:namespace" json:"namespace"`
	SiteName    string `gorm:"column:site_name" json:"site_name"`
	SystemType  string `gorm:"column:system_type" json:"system_type"`
	Port        int32  `gorm:"column:port" json:"port"`
	MetaData    string `gorm:"column:meta_data" json:"meta_data"`
}

// TableName CliNe's table name
func (*CliNe) TableName() string {
	return TableNameCliNe
}
