// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

import (
	"time"
)

const TableNameOauthAccessToken = "oauth_access_token"

// OauthAccessToken mapped from table <oauth_access_token>
type OauthAccessToken struct {
	TokenID          string    `gorm:"column:token_id" json:"token_id"`
	Token            []byte    `gorm:"column:token" json:"token"`
	AuthenticationID string    `gorm:"column:authentication_id;primaryKey" json:"authentication_id"`
	UserName         string    `gorm:"column:user_name" json:"user_name"`
	ClientID         string    `gorm:"column:client_id" json:"client_id"`
	Authentication   []byte    `gorm:"column:authentication" json:"authentication"`
	RefreshToken     string    `gorm:"column:refresh_token" json:"refresh_token"`
	TimeLogin        time.Time `gorm:"column:time_login" json:"time_login"`
	IPAddress        string    `gorm:"column:ip_address" json:"ip_address"`
	Expiration       time.Time `gorm:"column:expiration" json:"expiration"`
}

// TableName OauthAccessToken's table name
func (*OauthAccessToken) TableName() string {
	return TableNameOauthAccessToken
}
