// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_models

import (
	"time"
)

const TableNameTblAccount = "tbl_account"

// TblAccount mapped from table <tbl_account>
type TblAccount struct {
	AccountID         int64     `gorm:"column:account_id;primaryKey;autoIncrement:true" json:"account_id"`
	AccountName       string    `gorm:"column:account_name" json:"account_name"`
	Password          string    `gorm:"column:password" json:"password"`
	FullName          string    `gorm:"column:full_name" json:"full_name"`
	Email             string    `gorm:"column:email" json:"email"`
	Address           string    `gorm:"column:address" json:"address"`
	PhoneNumber       string    `gorm:"column:phone_number" json:"phone_number"`
	LoginFailureCount int32     `gorm:"column:login_failure_count" json:"login_failure_count"`
	ForceChangePass   bool      `gorm:"column:force_change_pass" json:"force_change_pass"`
	CreatedDate       time.Time `gorm:"column:created_date;not null" json:"created_date"`
	UpdatedDate       time.Time `gorm:"column:updated_date" json:"updated_date"`
	LastLoginTime     time.Time `gorm:"column:last_login_time" json:"last_login_time"`
	LastChangePass    time.Time `gorm:"column:last_change_pass" json:"last_change_pass"`
	Avatar            string    `gorm:"column:avatar" json:"avatar"`
	Status            bool      `gorm:"column:status;comment:delete: 0, live: 1" json:"status"` // delete: 0, live: 1
	DefaultDashboard  int32     `gorm:"column:default_dashboard" json:"default_dashboard"`
	AccountType       int32     `gorm:"column:account_type;comment:0-SuperAdmin ; 1-Admin ; 2-Normal" json:"account_type"` // 0-SuperAdmin ; 1-Admin ; 2-Normal
	AutoPassword      bool      `gorm:"column:auto_password" json:"auto_password"`
	Description       string    `gorm:"column:description" json:"description"`
	IsEnable          bool      `gorm:"column:is_enable;comment:1: active, 0: inactive" json:"is_enable"` // 1: active, 0: inactive
	CreatedBy         string    `gorm:"column:created_by" json:"created_by"`
	UpdatedBy         string    `gorm:"column:updated_by" json:"updated_by"`
	LockedTime        time.Time `gorm:"column:locked_time" json:"locked_time"`
	FirstLogin        []uint8   `gorm:"column:first_login" json:"first_login"`
	OnlyAD            bool      `gorm:"column:only_ad" json:"only_ad"`
	// PasswordExpiresAt is set on each password change based on the user's
	// effective password policy (max_age_days). Nil = never expires.
	PasswordExpiresAt *time.Time `gorm:"column:password_expires_at" json:"password_expires_at,omitempty"`
}

// TableName TblAccount's table name
func (*TblAccount) TableName() string {
	return TableNameTblAccount
}
